### ISSUE TITLE
Python 'AttributeError' when selecting crowdsourcing experiment

### ISSUE THREAD

**Issue by CNugteren** [ctuning/ck#78]
I'm trying to [autotune CLBlast using CK](https://github.com/ctuning/ck/wiki/Autotuning-example-clblast) (many thanks for setting this up in the first place!), but I'm encountering a Python AttributeError after selecting one of the 5 experiments when running `ck crowdtune clblast`:

```
************ Selecting program/benchmark/kernel ...

0) clblast-tune-trans (cb780bb2eda93e54)
1) clblast-tune-xgemm-direct-fp16 (4bafba9fbfd798b9)
2) clblast-tune-xgemm-direct-fp32 (85bb58b3b80f8a52)
3) clblast-tune-xgemm-fp16 (d4bc7ead4ebeaa9b)
4) clblast-tune-xgemm-fp32 (4437b9145862a46b)

Select UOA (or press Enter for 0): 0

  Selected program:          clblast-tune-trans (cb780bb2eda93e54)
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/ck/kernel.py", line 9146, in <module>
    r=access(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/ck/kernel.py", line 9102, in access
    rr=perform_action(i)
  File "/usr/local/lib/python3.4/dist-packages/ck/kernel.py", line 3301, in perform_action
    return a(i)
  File "/home/cnugteren/CK/ck-crowdtuning/module/clblast/module.py", line 53, in autotune
    return ck.access(i)
  File "/usr/local/lib/python3.4/dist-packages/ck/kernel.py", line 9102, in access
    rr=perform_action(i)
  File "/usr/local/lib/python3.4/dist-packages/ck/kernel.py", line 3301, in perform_action
    return a(i)
  File "/home/cnugteren/CK/ck-crowdtuning/module/experiment.tune.opencl.clblast/module.py", line 317, in crowdsource
    rr=ck.access(ii)
  File "/usr/local/lib/python3.4/dist-packages/ck/kernel.py", line 9102, in access
    rr=perform_action(i)
  File "/usr/local/lib/python3.4/dist-packages/ck/kernel.py", line 3301, in perform_action
    return a(i)
  File "/home/cnugteren/CK/ck-autotuning/module/program/module.py", line 3387, in pipeline
    r=ck.access(ii)
  File "/usr/local/lib/python3.4/dist-packages/ck/kernel.py", line 9102, in access
    rr=perform_action(i)
  File "/usr/local/lib/python3.4/dist-packages/ck/kernel.py", line 3301, in perform_action
    return a(i)
  File "/home/cnugteren/CK/ck-env/module/platform.os/module.py", line 158, in detect
    tosd.update(device_cfg.get('update_target_os_dict',{}))
AttributeError: 'str' object has no attribute 'get'
```

This is on a Debian machine with Python 3.4.2 and CK V1.9.1. I tried to go through the CK code to figure out what's going on, but I'm not familiar with the code so I couldn't figure it out. Let me know if there is any other information I should supply or if there is anything I can do myself.

**Comment by gfursin** [comment]
Thanks Cedric for report - I will check it this week (I have a feeling what happened). And thanks a lot to you for this nice library! Will keep in touch!

**Comment by gfursin** [comment]
Hi @CNugteren - I tried a clean installation and it seems to be working on my machine. Before digging deeper, may I ask you to update all repositories (I have a strange feeling that some may be outdated) and try it again:
```
$ ck pull all
$ ck crowdtune clblast
```
If error persists, I continue digging further ... Thanks a lot!

**Comment by CNugteren** [comment]
@gfursin Thanks, that solved the issue! I've actually done a full reinstall just to be sure.

**Comment by gfursin** [comment]
Cool! I actually added a note to update repositories to the documentation (completely forgot about it ;) ) !
