### ISSUE TITLE
`ck cp` doesn't correctly notify of a non-existent repo

### ISSUE THREAD

**Issue by dsavenko** [ctuning/ck#79]
Hi,

`ck cp some-repo-1:program:some-program some-repo-2:program:some-program` tells the following in case `some-repo-2` doesn't exists (may be, user made a typo in the repo name):

```
Traceback (most recent call last):
  File "/home/dsavenko/dvdt/ck/ck/kernel.py", line 9146, in <module>
    r=access(sys.argv[1:])
  File "/home/dsavenko/dvdt/ck/ck/kernel.py", line 9102, in access
    rr=perform_action(i)
  File "/home/dsavenko/dvdt/ck/ck/kernel.py", line 3301, in perform_action
    return a(i)
  File "/home/dsavenko/CK/ck-autotuning/module/program/module.py", line 5566, in cp
    ruid=r['repo_uid']
KeyError: 'repo_uid'
```

Expected: a clear message.

**Comment by gfursin** [comment]
The buggy function is actually not in the CK itself but overloaded in the module:program in the ck- autotuning repo. I just fixed it and will close this issue. Thanks for noting!
