### ISSUE TITLE
ck add repo:<...> --zip=~/<...> fails

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck#80]
Using `~`, the Unix shortcut for `$HOME`, in `ck add repo:<...> --zip=~<...>` results in a failure:
```
$ ck add repo:latest-experiments --zip=~/Downloads/latest-experiments.zip 
  Extracting to /home/anton/CK_REPOS/softmax-fused ...
 Traceback (most recent call last):
  File "/home/anton/CK/ck/kernel.py", line 9219, in <module>
    r=access(sys.argv[1:])
  File "/home/anton/CK/ck/kernel.py", line 9175, in access
    rr=perform_action(i)
  File "/home/anton/CK/ck/kernel.py", line 3318, in perform_action
    return a(i)
  File "/home/anton/CK/ck/repo/module/repo/module.py", line 356, in add
    rz=get_and_unzip_archive({'zip':zp, 'path':p, 'path_to_remove':ptr, 'overwrite':overwrite, 'out':o})
  File "/home/anton/CK/ck/repo/module/repo/module.py", line 1665, in get_and_unzip_archive
    f=open(zp,'rb')
IOError: [Errno 2] No such file or directory: '~/Downloads/latest-experiments.zip'
```
It works fine when providing the full path.

**Comment by gfursin** [comment]
I believe I fixed it - if you use version from GitHub, can you please try it and close this ticket if it works? Thanks!

**Comment by psyhtest** [comment]
Yes, received with thanks!
